### ISSUE TITLE
Unlock失败

### ISSUE THREAD

**Issue by itfanr** [jacket-code/redlock-cpp#3]
你好：

dlm->Unlock(my_lock);

我用一个进程Lock键foo，用另外的进程Unlock这个键，发现del未生效。这块可能存在bug。

**Comment by ifgoto** [comment]
delete未生效是应该的吧.如果另外的进程能删掉才有问题吧.

**Comment by itfanr** [comment]
@ifgoto  好久不看代码了  有可能你说的对  感谢
